---
- hosts: u
  become: yes
  gather_facts: False
  vars:
   - admin_user: pranab
   - admin_password: pranab123
  tasks: 
  
  - name: Package Update in Debian
    apt: 
      update_cache: yes
  
  - name: Install default JDK
    apt: 
      name: default-jdk
      state: present
  
  - name: Add tomcat Group
    group: 
      name: tomcat
      state: present
  
  - name: add tomcat user
    user:
      name: tomcat
      groups: tomcat
      shell: /bin/nologin 
      createhome: no

  - name: Download tomcat 
    get_url: 
      url: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.16/bin/apache-tomcat-8.5.16.tar.gz
      dest: /home/ansible/

  - name: Create A Directory /tmp/tomcat
    file:
      path: /tmp/tomcat/
      state: directory    
      owner: tomcat
      group: tomcat
      mode: 0774
      recurse: yes


  
  - name: Extract apache-tomcat-8.5.16.tar.gz to  
    command: tar xzvf apache-tomcat-8.5.16.tar.gz -C /tmp/tomcat/ --strip-components=1


  - name: Change the Owner & Group of Entire /opt/tomcat Directory
    file:
      path: /tmp/tomcat/
      owner: tomcat
      group: tomcat
      mode: 0774
      recurse: yes
  
  - name: Add JAVA_HOME path in /etc/environment file
    command: echo JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre" > /etc/environment 

  - name: copy tomcat.conf from server to node
    copy:
      src: tomcat.conf
      dest: /etc/init/tomcat.conf
      mode: 0755

  - name: reload-configuration
    command: initctl reload-configuration


#  - name:  start tomcat
#    command: initctl start tomcat

 # - name:  start tomcat
 #   command: initctl stop tomcat


  - name: copy tomcat-users.xml
    template: 
      src: /home/ansible/Devops/Ubuntu-Playbook/tomcat-users.j2
      dest: /opt/tomcat/conf/tomcat-users.xml

  - name: copy context.xml/manager
    template:
      src:  /home/ansible/Devops/Ubuntu-Playbook/tomcat-context.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

  - name: copy context.xml/Hostmanager
    template:
      src: /home/ansible/Devops/Ubuntu-Playbook/tomcat-context2host.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml


  - name: reload-configuration
    command: initctl reload-configuration
 
  - name:  Restart tomcat
    command: initctl restart tomcat







  




       


